server:
  port: 8888

spring:
  application:
    name: Banking-Config-Server
  cloud:
    config:
      server:
        native:
          search-locations: file:///D:/Study/App/Project1/properties

  profiles:
    active: native

